### ISSUE TITLE
Voyagers Update

### ISSUE THREAD

**Issue by Geldric** [goatfungus/NMSSaveEditor#1210]
This requires an update to the save editor. While basic functions still work and I can see my new custom built Corvette, none of the new parts are available nor can you read/access certain sections of the JSON data.

Thank you

**Comment by awkwrd** [comment]
As a first painter I approve the request. Corvettes should have some hull

**Comment by Maniac81358** [comment]
Si necesito esas partes y no soy bueno farmeando. A la espera del SaveEditor

**Comment by AstroCat00** [comment]
I hope get a Voyagers Update, possible?

**Comment by Geldric** [comment]
To help other impatient folks like myself:
https://steamcommunity.com/app/275850/discussions/0/601913886223958970/

**Comment by insert3coins** [comment]
Patience, Voyagers just came out 👯

**Comment by AstroCat00** [comment]
> Patience, Voyagers just came out 👯

No problem at all, just was wondering. :)

**Comment by jdm12983** [comment]
> Patience, Voyagers just came out 👯

Well, no point in really being "patient", as this program hasn't been updated sense before the LAST update. And it didn't have full support for everything then.

Sadly, this save editor is either abandoned, or something has happened to those that work on it.

NomNom finally got mostly updated for Beacons update [last update]. But, not even fully for that one according to the dev. But, it's still behind because it doesn't have anything for the current update.

Sucks either way; really love this editor out of the two.

**Comment by AstroCat00** [comment]
I guess one question is will it mess up my save game if I use it?

**Comment by Devilin-Pixy** [comment]
@Geldric :I have updated the info for missing name mappings in case anyone wishes to get into the raw JSON
See: https://github.com/goatfungus/NMSSaveEditor/issues/1200

**Comment by Devilin-Pixy** [comment]
For those eager to use all parts to build a corvette, you are all aware there are settings you can change? That will then allow to use all parts, regardless of having them. Can change settings after again if you wish.

**Comment by ghost** [comment]
> For those eager to use all parts to build a corvette, you are all aware there are settings you can change? That will then allow to use all parts, regardless of having them. Can change settings after again if you wish.

How? Explain pls

**Comment by Eeveermore** [comment]
> For those eager to use all parts to build a corvette, you are all aware there are settings you can change? That will then allow to use all parts, regardless of having them. Can change settings after again if you wish.

Please elaborate if you're going to alude to a solution.

**Comment by Geldric** [comment]
> For those eager to use all parts to build a corvette, you are all aware there are settings you can change? That will then allow to use all parts, regardless of having them. Can change settings after again if you wish.

? When the difficulty settings were first added to the game, whenever you lowered a setting (e.g make cost = 0), the game would add like an "*" to the end of your name (indicating that you lowered the diff setting). Does anyone know if that still happens? <- I generally set it to extreme difficulty and never look back.

**Comment by Geldric** [comment]
> I guess one question is will it mess up my save game if I use it?

I have used it extensively since Voyagers was released and it has never broken any of my save file(s)

**Comment by vectorcmdr** [comment]
Added a quick temp fix for inventory support of the new corvette components and the new mappings via PR #1212. You can grab the .jar from [my fork](https://github.com/vectorcmdr/NMSSaveEditor) or PR to use for now.

A rip of the icons would be welcome if anyone has time. Just using a placeholder for now.

**Comment by Devilin-Pixy** [comment]
@kam1cx @Eeveermore I am sorry, I thought I was clear. Just use the difficulty settings in-game, change crafting and purchasing to free and you should be able to create a Corvette with any part you wish. Of course default Creative mode works as well, as it includes these two settings and more.

**Comment by Teknikl** [comment]
> Patience, Voyagers just came out 👯

True but it's been months since an update dropped at all. The save editor is a few updates behind and also behind the NomNom save editor. The question is valid.

**Comment by vectorcmdr** [comment]
> > Patience, Voyagers just came out 👯
> 
> True but it's been months since an update dropped at all. The save editor is a few updates behind and also behind the NomNom save editor. The question is valid.

One of the reasons that community facing projects like this need active collaborators who can manage issues, review PRs, add features and maintain the repo when the owner is busy or the project is mothballed. It helps to keep things flowing.

Meanwhile, for anyone looking to add features I have a [copy of my fork with the unpacked source](https://github.com/vectorcmdr/NMSSaveEditor/tree/master-with-src) for editing. I encourage changes to be made and pull requests sent back to [the original repo](https://github.com/goatfungus/NMSSaveEditor).
If however, the original repo is effectively archived then it serves as a nice diving off point for a community contribution driven version with source openly available, unlike the present version and unlike NomNom.

**Comment by goatfungus** [comment]
New version 1.19.0 is now available.

Support added for new Corvette ships, which should be interesting.

Enjoy.

**Comment by denali1** [comment]
Looks like "Product/Building Part" is unavailable in Add Item?

<img width="390" height="297" alt="Image" src="https://github.com/user-attachments/assets/5091fdaa-271b-45d4-9b5f-95252a898175" />

**Comment by princeorion** [comment]
same, i see the items i already have but "building part" subcatagory is missing from the menu

**Comment by rak00001** [comment]
1.19.0 is where exactly? Not here?

**Comment by vectorcmdr** [comment]
> 1.19.0 is where exactly? Not here?

The usual place it is....

https://github.com/goatfungus/NMSSaveEditor/raw/master/NMSSaveEditor.exe
https://github.com/goatfungus/NMSSaveEditor/raw/master/NMSSaveEditor.zip
https://github.com/goatfungus/NMSSaveEditor/raw/master/NMSSaveEditor.jar

**Comment by jdm12983** [comment]
Nice to finally see some life back in this editor -- but seems like just a half-attempt just like the last update or two.

The editor has been "updated" to more or less work with the newest stuff. But, not all of it. Heck some items have been missing from the editor sense back in February this year.

**Comment by denali1** [comment]
> Nice to finally see some life back in this editor -- but seems like just a half-attempt just like the last update or two.
> 
> The editor has been "updated" to more or less work with the newest stuff. But, not all of it. Heck some items have been missing from the editor sense back in February this year.

I take it from your bottom comment that we should expect some commits from you soon?

**Comment by vectorcmdr** [comment]
> > Nice to finally see some life back in this editor -- but seems like just a half-attempt just like the last update or two.
> > 
> > The editor has been "updated" to more or less work with the newest stuff. But, not all of it. Heck some items have been missing from the editor sense back in February this year.
> 
> I take it from your bottom comment that we should expect some commits from you soon?

I totally agree with your sentiment for things like this, non-contributing complaints feel hollow and disrespectful
I do also think it's important to note that the project is in its essence unfortunately closed source, unless you decompile the jar each time and (if on Windows, deal with NTFS filename casing flags each time) which isn't major but is a hassle, and even then I am unsure if commits are welcome as a contrib stance isn't spelled out in the repo or by the owner.

I'd love to know if there is a possibility of a more contribution friendly repo moving forward. It seems like a net positive to me and would also help lock down a lot of noise generated here to have collaborators to triage issues.

**Comment by denali1** [comment]
> > > Nice to finally see some life back in this editor -- but seems like just a half-attempt just like the last update or two.
> > > The editor has been "updated" to more or less work with the newest stuff. But, not all of it. Heck some items have been missing from the editor sense back in February this year.
> > 
> > 
> > I take it from your bottom comment that we should expect some commits from you soon?
> 
> I totally agree with your sentiment for things like this, non-contributing complaints feel hollow and disrespectful I do also think it's important to note that the project is in its essence unfortunately closed source, unless you decompile the jar each time and (if on Windows, deal with NTFS filename casing flags each time) which isn't major but is a hassle, and even then I am unsure if commits are welcome as a contrib stance isn't spelled out in the repo or by the owner.
> 
> I'd love to know if there is a possibility of a more contribution friendly repo moving forward. It seems like a net positive to me and would also help lock down a lot of noise generated here to have collaborators to triage issues.

Agree with all points raised.  It just raises my hackles when people forget that projects like this are a labor of love rather than a job.  Too many projects have died due to the pressure from non-contributing and mal-contributing s*** stirrers that have an over developed sense of entitlement.  I don't want to see this happen to this project.  If there were a way to make this where contributing could be easier and it would take pressure off of goatfungus (and it was something he wanted), that would be awesome in my opinion.  Ultimately, I don't have a vote in this.

**Comment by jdm12983** [comment]
Well, seeing as this had been my go-to save editor for the longest time; but hasn't been fully updated sense at least February - guess I will move on. Can't wait to see all the amazing progress you two make with your positivity you bring.

I have posted back in February about missing stuff; no response. Sense then there have been at least two updates to support major updates; while not bothering to add in those missing items. Now, after several months of nothing we get a sudden quick update to partially support this update and now a section of "add items" pop up is missing. Making the editor further broken.

I have no where said that the dev needs to work on this non-stop or that they are horrible.  Just the fact if they aren't able to fully update it anymore - which is fine, they have a life - why do partial updates that still don't add items missing from way back earlier this year?


If this editor gets fully updated to add in all the missing stuff; great. Otherwise, NomNom is a great secondary choice.

**Comment by vectorcmdr** [comment]
I have another unofficial hotfix for missing mappings and corvette part search via PR #1230.
Users can grab the .exe, .jar or .zip from the PR or from [the fork](https://github.com/vectorcmdr/NMSSaveEditor/tree/master) via the [zip](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.zip) until it's merged or independently officially updated.

Note: It will say there is a newer version available for update as this hotifx version number (1.19.1) doesn't match the official published version (1.19.0) and is a string comparison. You should ignore the auto update request if using it.

**Comment by balldufa** [comment]
> I have another unofficial hotfix for missing mappings and corvette part search via PR [#1230](https://github.com/goatfungus/NMSSaveEditor/pull/1230). Users can grab the .exe, .jar or .zip from the PR or from [the fork](https://github.com/vectorcmdr/NMSSaveEditor/tree/master) via the [zip](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.zip) until it's merged or independently officially updated.
> 
> Note: It will say there is a newer version available for update as this hotifx version number (1.19.1) doesn't match the official published version (1.19.0) and is a string comparison. You should ignore the auto update request if using it.

Sorry, I installed your solution and the adding parts still doesn't work.

https://i.postimg.cc/ds8r28dw/Captura-de-pantalla-2025-09-01-163955.png

**Comment by vectorcmdr** [comment]
> Sorry, I installed your solution and the adding parts still doesn't work.
> 
> https://i.postimg.cc/ds8r28dw/Captura-de-pantalla-2025-09-01-163955.png

Odd, it should be. They're under customisation parts, like normal starship components are:
<img width="661" height="202" alt="Image" src="https://github.com/user-attachments/assets/71e7e197-28cd-4859-88c5-ae4b6b79e4d6" />
<img width="421" height="198" alt="Image" src="https://github.com/user-attachments/assets/71491207-43c6-4887-94bd-243564f853bc" />

**Comment by balldufa** [comment]
> > Lo siento, instalé tu solución y las partes de adición aún no funcionan.
> > https://i.postimg.cc/ds8r28dw/Captura-de-pantalla-2025-09-01-163955.png
> 
> Es raro, debería serlo. Están bajo partes de personalización, como los componentes de naves estrelladas normales son: <img alt="Imagen" width="661" height="202" src="https://private-user-images.githubusercontent.com/7644256/484260279-71e7e197-28cd-4859-88c5-ae4b6b79e4d6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY3NDAyNDIsIm5iZiI6MTc1NjczOTk0MiwicGF0aCI6Ii83NjQ0MjU2LzQ4NDI2MDI3OS03MWU3ZTE5Ny0yOGNkLTQ4NTktODhjNS1hZTRiNmI3OWU0ZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MDFUMTUxOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY5MjAwZWVkZjlkYWEwZDMyODc3OTE3NTZhYTM0ODM1YWU1OWE2N2VkNTI5ZGM2ZjFiOWZlMjU0NDMwYWI0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dWgSJpJu2MnpEtJmguCa23wbgrrqqY8IvhKF6thusPI"><img alt="Imagen" width="421" height="198" src="https://private-user-images.githubusercontent.com/7644256/484260556-71491207-43c6-4887-94bd-243564f853bc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY3NDAyNDIsIm5iZiI6MTc1NjczOTk0MiwicGF0aCI6Ii83NjQ0MjU2LzQ4NDI2MDU1Ni03MTQ5MTIwNy00M2M2LTQ4ODctOTRiZC0yNDM1NjRmODUzYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MDFUMTUxOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWNhNGEwNjQ5NGIzYmY4NzQ4N2QwMjNmOWY4ZTMwYjVjZjA3NTFhMmVmMTJlOTU3MmMzYzE5NmE0OTViYzQwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NCDpxYWY1WL_x-zEzviRPWMcZRVsfcjtI7-EoAd5haM">

I already fixed it. I wasn't modifying the *.*.jar, which is why it wasn't installing all the modified files.
Thanks, and sorry for my mistake.

**Comment by Essemtea** [comment]
> > Sorry, I installed your solution and the adding parts still doesn't work.
> > https://i.postimg.cc/ds8r28dw/Captura-de-pantalla-2025-09-01-163955.png
> 
> Odd, it should be. They're under customisation parts, like normal starship components are: <img alt="Image" width="661" height="202" src="https://private-user-images.githubusercontent.com/7644256/484260279-71e7e197-28cd-4859-88c5-ae4b6b79e4d6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY4MzM3ODUsIm5iZiI6MTc1NjgzMzQ4NSwicGF0aCI6Ii83NjQ0MjU2LzQ4NDI2MDI3OS03MWU3ZTE5Ny0yOGNkLTQ4NTktODhjNS1hZTRiNmI3OWU0ZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MDJUMTcxODA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJmYjA5ZmFjYmYzOWUwMjIzMTZlYTMwYjc2NmRhMjc4YjE2OWVmYWZlZGU2N2NiOGUzNzllNTEyZWFmMmNkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.g3IUHgxGHgaENJtpugPNkclsXNDHjcRG49H7SN737uo"> <img alt="Image" width="421" height="198" src="https://private-user-images.githubusercontent.com/7644256/484260556-71491207-43c6-4887-94bd-243564f853bc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY4MzM3ODUsIm5iZiI6MTc1NjgzMzQ4NSwicGF0aCI6Ii83NjQ0MjU2LzQ4NDI2MDU1Ni03MTQ5MTIwNy00M2M2LTQ4ODctOTRiZC0yNDM1NjRmODUzYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MDJUMTcxODA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjMzOGZhODE3NWY5MjEyYmRhYTBlMTViZjg0ZjcxNDAzZmVjNDU1MzY2NmY4ZmFkYzFjMmRiYTJlMTVmMDU2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fVnn_AH_zWHpcuMD95BQFxnzwRBSupJytdf9fs__9OM">

Not sure if it's on my end, but a lot of components seem to be missing from the CUSTOMIZATION_PART category (e.g. most Titan parts) and are still in BUILDING_PART according to the items.xml db file. I tried adjusting the mappings manually but it throws an exception over "nomanssave.ex.CUSTOMIZATION_PART" not being a registered enum (despite the correctly mapped parts working fine). Wasn't sure if you were already aware or not, or if it was my fault, but thanks either way for working to update this so fast!

**Comment by vectorcmdr** [comment]
> Not sure if it's on my end, but a lot of components seem to be missing from the CUSTOMIZATION_PART category (e.g. most Titan parts) and are still in BUILDING_PART according to the items.xml db file. I tried adjusting the mappings manually but it throws an exception over "nomanssave.ex.CUSTOMIZATION_PART" not being a registered enum (despite the correctly mapped parts working fine). Wasn't sure if you were already aware or not, or if it was my fault, but thanks either way for working to update this so fast!

Nope it wasn't you, it was borked. Thanks for letting me know.
There was a section of the ```items.xml``` that I missed changing over which meant there was a selection of parts still missing.

Corrected on the [fork](https://github.com/vectorcmdr/NMSSaveEditor) and the [pull request](https://github.com/goatfungus/NMSSaveEditor/pull/1230) now.
You can grab the new 7zip [.exe](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.exe) to get the updated ```.jar``` etc.
Version bumped to 1.19.2. Same note as before for ignoring auto update prompt until official update/merge.

<img width="490" height="258" alt="Image" src="https://github.com/user-attachments/assets/945b17a4-5238-4b0e-93cd-0d6648be56eb" />

~~_**Note:** 
Incoming NMS Experimental patch has a larger stack size for corvette parts (50), so be aware of this until/if it makes it to NMS Official and then to here if playing on Experimental._~~

**Comment by vectorcmdr** [comment]
Hello all,
I have updated my [fork](https://github.com/vectorcmdr/NMSSaveEditor) and pull request #1230 again for the NMS 6.03 update.
Corvette part stack size has been increased per the NMS update.

You can grab the unofficial hotfix [.exe](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.exe) [.zip](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.zip) or just the [.jar](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.jar) file from the [forked repo](https://github.com/vectorcmdr/NMSSaveEditor) until it's officially updated or merged.

Version bumped to 1.19.3. As before, please ignore the auto update prompt on startup as it won't be correct until the official main matches or is higher.

Happy interloping! 🚀

**Comment by MissChaos7000** [comment]
First, thanks for your work on this project @vectorcmdr .
I see the corvette building parts in the menu multiple times.
[![Bildschirmfoto-2025-09-04-um-11-13-41.png](https://i.postimg.cc/dVpQZNMG/Bildschirmfoto-2025-09-04-um-11-13-41.png)](https://postimg.cc/w15YSVjB)

**Comment by vectorcmdr** [comment]
I believe it's the different rotations, as they're now a group of individual items due to the rotation non-refund bug that NMS 6.0 had until the recent bug fix. Let me know if it appears otherwise.

Edit: Just got some time to double checked and yes, it's the flipped and mirrored variants.
They're not named differently in game to denote the orientation and are consumed the same, so you can just pick any of the iterations and use them. It's annoying that there are 16 of some, but it's as intended.

**Comment by vectorcmdr** [comment]
Another minor update to my [fork](https://github.com/vectorcmdr/NMSSaveEditor) and pull request #1230 again.

Added the second Vesper Diffuser type due to the rotate/refund NMS bug fix.
Adds support for items:
```
 ^B_STR_M_NE
 ^B_STR_M_NE1
 ^B_STR_M_NE2
 ^B_STR_M_NE3
 ^B_STR_M_NW
 ^B_STR_M_NW1
 ^B_STR_M_NW2
 ^B_STR_M_NW3
```

You can grab the unofficial hotfix [.exe](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.exe) [.zip](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.zip) or just the [.jar](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.jar) file from the [forked repo](https://github.com/vectorcmdr/NMSSaveEditor) until it's officially updated or merged.

Version bumped to 1.19.4. Again, as before please ignore the auto update prompt on startup as it won't be correct until the official main matches or is higher.

**Comment by vectorcmdr** [comment]
Bumped 1.19.5 to include Thermal Grille Cap inventory items ('_valid_' orientations only):
```
^B_STR_N_NE
^B_STR_N_NE1
^B_STR_N_NE2
^B_STR_N_NE3
^B_STR_N_NW
^B_STR_N_NW1
^B_STR_N_NW2
^B_STR_N_NW3
```
You can grab the unofficial hotfix [.exe](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.exe) [.zip](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.zip) or just the [.jar](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.jar) file from the [forked repo](https://github.com/vectorcmdr/NMSSaveEditor) until it's officially updated or merged.
Ignore the update warning, yada yada.

Edit:
An explainer for only including 8 of 16 variants for items like these:
Orientations for some parts can be expressed like below...
```
rot(0,0,0), scale(1,1,1)
rot(0,0,0), scale(1,-1,1)
rot(0,0,0), scale(-1,1,1)
rot(0,0,0), scale(-1,-1,1)
rot(0,90,0), scale(1,1,1)
rot(0,90,0), scale(-1,1,1)
rot(0,90,0), scale(-1,-1,1)
rot(0,90,0), scale(1,-1,1)
rot(0,180,0), scale(1,1,1)
rot(0,180,0), scale(1,-1,1)
rot(0,180,0), scale(-1,1,1)
rot(0,180,0), scale(-1,-1,1)
rot(0,270,0), scale(1,1,1)
rot(0,270,0), scale(-1,1,1)
rot(0,270,0), scale(-1,-1,1)
rot(0,270,0), scale(1,-1,1)
```
16 versions, 1 for each orientation.
But not all parts that can be used this way appear to be player facing and/or finalized in game when in the inventory due to the initial 6.0 bugs and the bug fixes for rotation and part refunding.
I'm personally of the opinion that there is no point including the additional 8 that aren't supposed to be exposed to the player for now, but open to input.

**Comment by vectorcmdr** [comment]
New unofficial hotfix build 1.19.6 available [from my fork](https://github.com/vectorcmdr/NMSSaveEditor) while we await an official update.

Grab the [.exe](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.exe), [.zip](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.zip) or [.jar](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.jar) - or grab it from the forks [releases tab](https://github.com/vectorcmdr/NMSSaveEditor/releases/tag/1.19.6).

1.19.6 has the new mappings for Expedition 19 added as noted in Issue #1231 
```
kKt	ForceReplaceStoryPortalSeed
:N6	SearchType
PBQ	SpecificBuildingClass
04i	UseBuildingFromRendezvousStage
l;o	NeedsDeepWaterPlanet
iIi	ExcludePlanetsWithEvents
Eaw	SystemNeedsGasGiant
o1O	NeverAllowGasGiantSystem
BFN	AltDescription
;lF	BuildableShipTechID
SuM	FossilCategory
96H	CorvettePartCategory
DTD	NeverPinnable
eSZ	FoodBonusStat
N=w	StatsType
<:g	FoodBonusStatAmount
```

**Comment by vectorcmdr** [comment]
New unofficial hotfix build 1.19.7 available [from my fork](https://github.com/vectorcmdr/NMSSaveEditor) while we await an official update.

Grab the [.exe](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.exe), [.zip](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.zip) or [.jar](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.jar) - or grab it from the forks [releases tab](https://github.com/vectorcmdr/NMSSaveEditor/releases/tag/1.19.7).

1.19.7 has the new account mappings from experimental 09/09 (6.05) as per Issue #1231 
```
>W7 CustomBindingsMac
Jxp CustomBindingsPC
MyN CustomBindingsPlaystation
jSo CustomBindingsSwitch
ilV CustomBindingsXbox
```

**Comment by balldufa** [comment]
> Nueva construcción de hotfix no oficial 1.19.7 disponible [de mi tenedor](https://github.com/vectorcmdr/NMSSaveEditor) mientras esperamos una actualización oficial.
> 
> Agarra el [.exe](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.exe), [.zip](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.zip) o [.jar](https://github.com/vectorcmdr/NMSSaveEditor/blob/master/NMSSaveEditor.jar) - o agárralo de las horquillas [la pestaña.](https://github.com/vectorcmdr/NMSSaveEditor/releases/tag/1.19.7)
> 
> 1.19.7 tiene las nuevas asignaciones de cuenta de la versión experimental 09/09 (6.05) según la edición [1231](https://github.com/goatfungus/NMSSaveEditor/issues/1231)
> 
> ```
> >W7 CustomBindingsMac
> Jxp CustomBindingsPC
> MyN CustomBindingsPlaystation
> jSo CustomBindingsSwitch
> ilV CustomBindingsXbox
> ```

yo no se los demas, pero yo voy ha felicitar tu labor y darte las gracias por el esfuezo. Gracias

**Comment by vectorcmdr** [comment]
Gracias, me alegro de poder ayudar.
