### ISSUE TITLE
WARNING: name mapping not found: 5LX

### ISSUE THREAD

**Issue by k5jat** [goatfungus/NMSSaveEditor#236]
I got this after the 2.26 update and loading up a recently saved save file.

**Comment by Siino** [comment]
That's the parameter for the new jetpack trails they added. 
Going to a character customization station to set the default trail (smoke) then saving in game should fix it.

**Comment by k5jat** [comment]
It didn't fix it. I went to the customization station on the Nexus and just loaded up that save. It's the same error.

**Comment by Axel-Vbg** [comment]
weird, used the editor yesterday and didn't get it, i even edited my save to add the new trails that are not even unlocked yet to try them and it all worked fine

**Comment by Siino** [comment]
Weird, I used the editor yesterday and didn't have it, I even added the new Quicksilver items that are not unlocked yet to test these trails, and it all worked fine

**Comment by k5jat** [comment]
This is an warning in the console when I run from the batch file. I'm sorry I left that out in my report. My guess is that it just means the 5LX isn't in the reference map for the editor since it's new?

**Comment by roie-r** [comment]
The warning means HG added new objects to the save file's structure and the editor needs updating. You can still use it safely though.

**Comment by goatfungus** [comment]
This is fixed in the latest update, 1.6.9.
