### ISSUE TITLE
Java error on loading save file and ships won't import

### ISSUE THREAD

**Issue by DarthRogue** [goatfungus/NMSSaveEditor#343]
After the Next Generation update released on Nov 10 the save editor receives an error when loading in my save files.  Also gets an error when trying to load in a saved ship.  See screenshot for reference.  

![java error NMS](https://user-images.githubusercontent.com/5487556/100317159-dbd31180-2f89-11eb-9b8a-4082277832be.PNG)

Happens on multiple save files.  Tried downloading a fresh copy of the editor but the problem persists.  My PC has both Java 32-bit and 64-bit runtimes from latest Java version.

**Comment by DarthRogue** [comment]
Resolved in newest version.

**Comment by BigGrayGolem** [comment]
Problem is back in save editor version 1.10.7. Cannot import ships.
