### ISSUE TITLE
Discovery and Account tabs messed up.

### ISSUE THREAD

**Issue by Pablo-Diablo** [goatfungus/NMSSaveEditor#437]
The Discovery and Account tabs don't function correctly. When you select either one they seem to be blanc until you wiggle the mouse a bit and values will start popping up.
The command window also prints a lot of errors when you start the save editor.
I tried redownloading the editor and reinstalling Java to no avail.

**Comment by goatfungus** [comment]
Can you please attach the error log?

**Comment by Pablo-Diablo** [comment]
> Can you please attach the error log?

Certainly.
[nmsse.txt](https://github.com/goatfungus/NMSSaveEditor/files/7146361/nmsse.txt)

**Comment by goatfungus** [comment]
It looks like your save data is not compressed according to the standard save file format as they should start with the following:
{"F2P":5159

How old are these particular save files?

**Comment by goatfungus** [comment]
I'll put in some detection for the older format, but I don't think that is the same issue.... can you send me the save file itself and I'll check it out.

**Comment by Pablo-Diablo** [comment]
Now that I'm looking at it it looks like the errors do relate to the save files themselves... Those are from Expedition 1 and 2 which I haven't visited since they were over. My original save file is from day 1 though and it works! Well, it works only because of you app because there were countless game breaking progress stopping bugs that couldn't be fixed otherwise.

**Comment by Pablo-Diablo** [comment]
These save files show up as empty in NMSSE
[nmsse.zip](https://github.com/goatfungus/NMSSaveEditor/files/7146480/nmsse.zip)
And they in fact are not from the old Expeditions but from a week ago.

**Comment by goatfungus** [comment]
Those are just the manifest files, can you include the save5.hg and save3.hg files too?

**Comment by goatfungus** [comment]
I have a suspicion that the companions tab is throwing an error, which would be why the tabs after it are messed up... i just need to see an example of a save file where that occurs and it should be an easy fix.

**Comment by Pablo-Diablo** [comment]
Oups...
[mnsse1.zip](https://github.com/goatfungus/NMSSaveEditor/files/7146500/mnsse1.zip)

**Comment by goatfungus** [comment]
Ok... it looks like both of those save files are from 2017 (last modified date) and they are missing a whole bunch of structures that the editor uses.... i suggest you try to open them in-game then allow the game itself to save it to the new format in the meantime, as the editor cannot do the conversion itself.

**Comment by Pablo-Diablo** [comment]
Sorry, this is probably misleading... the above file are very old save files and not the recent expedition ones... I can't reproduce the bug on those because they would simply not open... Even the game itself got kinda glitchy after I loaded them. The visual bug in MNSSE is reproducible on this save for example.
[save11.zip](https://github.com/goatfungus/NMSSaveEditor/files/7146557/save11.zip)

**Comment by goatfungus** [comment]
Have you got the mf_save11.hg file too?

**Comment by Pablo-Diablo** [comment]
[mf_save11.zip](https://github.com/goatfungus/NMSSaveEditor/files/7146624/mf_save11.zip)
Sure.

**Comment by goatfungus** [comment]
Ok, I believe I have fixed the problem now in update 1.8.4. Enjoy.

**Comment by Viexi** [comment]
Hi @goatfungus, unfortunately the new fix still experiences issues with the Account tab
![image](https://user-images.githubusercontent.com/90485186/132928991-298c8d1f-7aea-4241-9cae-23edcb7448ba.png)

What do you need from me to diagnose?

**Comment by goatfungus** [comment]
OMG... I'm an idiot sometimes.
Easy fix, try version 1.8.6!

**Comment by Viexi** [comment]
@goatfungus Amazing, that's done it! Incredible turnaround, thank you so much!

**Comment by Pablo-Diablo** [comment]
The tabs still don't work for me. Here is an error codes of when I just click on the Discovery tab.
[1.txt](https://github.com/goatfungus/NMSSaveEditor/files/7146982/1.txt)

**Comment by goatfungus** [comment]
@Pablo-Diablo which save file is it that you are getting that error on?

**Comment by Pablo-Diablo** [comment]
@goatfungus all save files have that including the one I sent you. But I can now open those really old save files.

**Comment by goatfungus** [comment]
Ok, so its all working now then?

**Comment by Pablo-Diablo** [comment]
Sadly, no. The visual bug is still present.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
