### ISSUE TITLE
NMS Omega 4.5 update - Save file corrupted

### ISSUE THREAD

**Issue by SplinterGU** [goatfungus/NMSSaveEditor#923]
All saved files from NMS Omega 4.5 Update don't load and display a message box with text "Save file corrupted"

**Comment by danishroohul** [comment]
Facing the same error

**Comment by danishroohul** [comment]
![image](https://github.com/goatfungus/NMSSaveEditor/assets/38494862/877da567-5b1d-41d2-913d-b7b23f2ae718)

**Comment by danishroohul** [comment]
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/14301240/NMSSaveEditor.log)

**Comment by SmallMegazord** [comment]
The only thing you can do currently is roll back to a previous save (hopefully within a day or two) . Add what ever you need, load up on the things you need. You can even do a "Save As" to copy within the save editor, and keep the original save untouched just incase you forgot something and play off that save. You will not be able to edit anything or save that new save properly until you load into the game and load into that save. Load out of the game but keep the save editor up and running. Load out of the game save then go to the save editor. It will ask you if you would like to update and you say no. Then you will have the option to then save within the save editor and then modify the copied game save. It will double up the name but you should be able to edit the json file and call it -2 or something so you can keep track of it. 

As soon as you load into the game with the Omega version the game and a save is made it will be seen as corrupted and you will no longer be able to edit. We will just have to hope this is either addressed or goatfungus will be able to crack this and we will be able to access the save edit with the new format for the hg files.

**Comment by SplinterGU** [comment]
> The only thing you can do currently is roll back to a previous save (hopefully within a day or two) . Add what ever you need, load up on the things you need. You can even do a "Save As" to copy within the save editor, and keep the original save untouched just incase you forgot something and play off that save. You will not be able to edit anything or save that new save properly until you load into the game and load into that save. Load out of the game but keep the save editor up and running. Load out of the game save then go to the save editor. It will ask you if you would like to update and you say no. Then you will have the option to then save within the save editor and then modify the copied game save. It will double up the name but you should be able to edit the json file and call it -2 or something so you can keep track of it.
> 
> As soon as you load into the game with the Omega version the game and a save is made it will be seen as corrupted and you will no longer be able to edit. We will just have to hope this is either addressed or goatfungus will be able to crack this and we will be able to access the save edit with the new format for the hg files.

The new saved game from the game works fine (in the game, it's not actually corrupted). The problem is not being able to edit it because the editor detects it as corrupted. It's not useful to make a copy and edit the original and use "save as" because I lose progress in the game... the idea is that this works. Thanks!

**Comment by kobs57** [comment]
GF is probably working on getting all the new stuff and gadget at the same time for the Omega. I know it seems like a long time I'm also waiting, checking 2 or 3 times a day loll it'll be fun when it comes ; )

**Comment by SplinterGU** [comment]
I don't know why it fail with nmssaveeditor... I just now decode a savegame and it decode fine... look...

![image](https://github.com/goatfungus/NMSSaveEditor/assets/95715426/96066f8c-1d5c-4877-8430-e1b98bc6f22d)

**Comment by SplinterGU** [comment]
> GF is probably working on getting all the new stuff and gadget at the same time for the Omega. I know it seems like a long time I'm also waiting, checking 2 or 3 times a day loll it'll be fun when it comes ; )

yes, we must wait! thanks!

**Comment by HedgeHog2222** [comment]
> I don't know why it fail with nmssaveeditor... I just now decode a savegame and it decode fine... look...
> 
> ![image](https://private-user-images.githubusercontent.com/95715426/305264502-96066f8c-1d5c-4877-8430-e1b98bc6f22d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODU5NzAsIm5iZiI6MTcwODA4NTY3MCwicGF0aCI6Ii85NTcxNTQyNi8zMDUyNjQ1MDItOTYwNjZmOGMtMWQ1Yy00ODc3LTg0MzAtZTFiOThiYzZmMjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDEyMTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxOTE1ZWU0ZTczMGNiMTU4YmJkODkwNmQ1MDA3MDM4ZDY2MGM4MGY4NGZmOWJiODdmZTI2NzRjNTVmMGZkMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BRuiG0eqx5G1mAJcHDvQv7_ZLHMukgfZbwoiYfXA67s)

I hope so. Are they still active?

**Comment by HedgeHog2222** [comment]
> GF is probably working on getting all the new stuff and gadget at the same time for the Omega. I know it seems like a long time I'm also waiting, checking 2 or 3 times a day loll it'll be fun when it comes ; )

Is GF still active?

**Comment by kobs57** [comment]
> > GF is probably working on getting all the new stuff and gadget at the same time for the Omega. I know it seems like a long time I'm also waiting, checking 2 or 3 times a day loll it'll be fun when it comes ; )
> 
> Is GF still active?

I sure hope so lol, he's the one making updates. I'd go nuts if I had to play without, now that I'm used to this program

**Comment by PossiblyNocturnal** [comment]
> I don't know why it fail with nmssaveeditor... I just now decode a savegame and it decode fine... look...
> 
> ![image](https://private-user-images.githubusercontent.com/95715426/305264502-96066f8c-1d5c-4877-8430-e1b98bc6f22d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDg1NzEsIm5iZiI6MTcwODEwODI3MSwicGF0aCI6Ii85NTcxNTQyNi8zMDUyNjQ1MDItOTYwNjZmOGMtMWQ1Yy00ODc3LTg0MzAtZTFiOThiYzZmMjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE4MzExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYzUxMmY1YjhlNTRkZjhjZmEyMmJlM2RjMTkwOTk4YmUwMTg0Zjk0MjU1OWFlMDdkNzJhMTM3ZDFkOWE0MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ki7_xNkGVn_jIpDuSqW3pdwl1hvkpSOACWU5T5soAKw)

Not really related to 4.5 breaking nmsse, but how do you manually decode a nms save?

**Comment by goatfungus** [comment]
Hi all, thanks for your patience. I'm currently working on the updates for OMEGA, which should be ready in the next few days.

**Comment by louanfontenele** [comment]
> Hi all, thanks for your patience. I'm currently working on the updates for OMEGA, which should be ready in the next few days.

Thank you.

**Comment by goatfungus** [comment]
I have just pushed up a new version, 1.15.0, which gets around the "file corrupted" error, and adds a few new items, etc from the game files. Please use with care and backup your saves!

I will be keeping an eye on things to see if anything else is broken with the new save format.

**Comment by Zafford** [comment]
Still get the "Corrupt" messsage with the new version - is there something else I have to do with the save?

**Comment by goatfungus** [comment]
> Still get the "Corrupt" messsage with the new version - is there something else I have to do with the save?

Can you send me the save file and log?

**Comment by Zafford** [comment]
> > Still get the "Corrupt" messsage with the new version - is there something else I have to do with the save?
> 
> Can you send me the save file and log?

Mail sent with the files

**Comment by rgiles18a** [comment]
The new version, 1.15.0 is working for me. Thanks goatfungus, you're the best!!

**Comment by goatfungus** [comment]
> Still get the "Corrupt" messsage with the new version - is there something else I have to do with the save?

There is an entirely different structure for expedition saves, which I have added just now. Let me know if you have any issues with version 1.15.1.

**Comment by Zafford** [comment]
> > Still get the "Corrupt" messsage with the new version - is there something else I have to do with the save?
> 
> There is an entirely different structure for expedition saves, which I have added just now. Let me know if you have any issues with version 1.15.1.

Works for me now - many thanks

**Comment by ThunderStruck5966** [comment]
Thank you Goatfungus all seems to be working fine again.

Much appreciated

**Comment by RaYaAn7762** [comment]
it Lives!!! You are a steely eyed missile man!

**Comment by Callisto649** [comment]
Thanks a lot. That’s after-sales service premium ;-)

**Comment by Giozee** [comment]
I was playing on an expedition savegame (i don't own the game. I'm playing with the free weekend) tried editing the savegame and the slot was changed from "expedition" to "normal".
Can't access the savegame from the game anymore without buying the game.
I thought my mistake was doing something specific, but i'm pretty sure the save editor changes from expedition to normal or custom at any change. (Ok, yeah. While writing this i sacrificed another savegame to the cause: made a new expedition savegame, edited a quantity in my inventory from 30 to 31 and saved. not an expedition save anymore.)
<img width="331" alt="image" src="https://github.com/goatfungus/NMSSaveEditor/assets/64650196/adbcf3bb-39a6-403c-80fa-5b399e7c4835">

**Comment by SplinterGU** [comment]
> > I don't know why it fail with nmssaveeditor... I just now decode a savegame and it decode fine... look...
> > ![image](https://private-user-images.githubusercontent.com/95715426/305264502-96066f8c-1d5c-4877-8430-e1b98bc6f22d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDg1NzEsIm5iZiI6MTcwODEwODI3MSwicGF0aCI6Ii85NTcxNTQyNi8zMDUyNjQ1MDItOTYwNjZmOGMtMWQ1Yy00ODc3LTg0MzAtZTFiOThiYzZmMjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE4MzExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYzUxMmY1YjhlNTRkZjhjZmEyMmJlM2RjMTkwOTk4YmUwMTg0Zjk0MjU1OWFlMDdkNzJhMTM3ZDFkOWE0MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ki7_xNkGVn_jIpDuSqW3pdwl1hvkpSOACWU5T5soAKw)
> 
> Not really related to 4.5 breaking nmsse, but how do you manually decode a nms save?

with several tools that I made...

**Comment by SplinterGU** [comment]
> > Still get the "Corrupt" messsage with the new version - is there something else I have to do with the save?
> 
> There is an entirely different structure for expedition saves, which I have added just now. Let me know if you have any issues with version 1.15.1.

expedition savedgame works fine for me! thanks!
