### ISSUE TITLE
All Omega saves display as empty and throw a error when you try to load them, 1.15.2

### ISSUE THREAD

**Issue by meglomainiac** [goatfungus/NMSSaveEditor#962]
All Omega saves display as empty and throw a error when you try to load them.

You can still edit saves that were saved before Omega but any that were created after or loaded and saved after the update can't been seen or edited in 1.15.2.

**Comment by Ecchieving** [comment]
Im having the same issue sadly, no idea how to get this to work. Do you play on gamepass or steam version? I'm on gamepass

**Comment by meglomainiac** [comment]
It has trouble reading the save with the new Omega format as you can convert your save to a expedition save and back again.

I have both but I am using gamepass at the moment. You can use nomnom if you need to edit your save, it doesn't have as many options and crashes sometimes but it is the only way at the moment until Goatfungus updates his save editor.

**Comment by oom-is** [comment]
I will note for the record that on PC/Steam I have had zero issues editing saves that completed the expedition, or even editing in the middle of the expedition.  This applies both to previous saves that started the expedition from the Anomaly, and to new saves created for the expedition.
Please, folks, when reporting a bug make sure to include your platform?  The context will really help when someone goes to track down issues.  I'm speculating at this point that there is an incompatible file format change that affects XBox and GamePass (which are sort of the same thing) but doesn't affect most (any?) Steam users.

**Comment by spideruk07** [comment]
Steam and GOG on pc are fine it's only Xbox and Xbox pc that are affected

**Comment by meglomainiac** [comment]
You have zero idea what you are talking about, had you said PC/Windows or PC/Linux you would have been right. Considering most people that play on the PC platform run windows, unless otherwise stated that you are running Linux then it safe to assume it's windows.

Now it states that both the hardware or associated operating system, not random applications or programs.

Platform:

"A computer or hardware device and/or associated operating system, or a virtual environment, on which software can be installed or run."

You don't install the games on Gog or Steam ... you install them on your computer, Gog and steam aren't virtual PC's.

At least know what you are talking about before you try to convince others.

**Comment by oom-is** [comment]
Congratulations - I bow to your superior ability to find citations that support your opinions.

But the facts are that if folks would include "PC/Steam" or "Xbox" or "XBox Game Pass on PC" in their bug reports then the maintainer would have a better chance of finding and fixing bugs.

Can you at least agree with that point?  Because that's all that matters.
Provide a bug report that has sufficient detail, or GTFO.
Unsubscribing from this issue report.

**Comment by meglomainiac** [comment]
You are either extremely stupid or a troll.

It's not a opinion it is a fact, one that even in your ignorance you could have easily looked up.

From your delusions and lack of understanding what words mean it's pretty easy to guess what country you are from.

Discussing this with you any longer is waste of time and cluttering this thread for no reason, so I won't bother replying to you in the future.

**Comment by goatfungus** [comment]
Guys, please be civil.

I don't care what "correct terminology" you want to prescribe to, but the fact of the matter is that the save files produced by the Steam version are a different format to those produced by Gog, Xbox, etc. Since I only have the Steam version, that is the primary version I built this editor for.

Having said that, I have added support for other file formats such as Gog and Xbox Game Pass as well and will continue to do so. Since they are also subject to change by HG without warning I have to rely on this community to provide samples of their save file data so that I can continue supporting those versions, so feel free to email your save files to me but just be aware that updates for those versions may not come as quickly as the Steam ones since I am unable to test them myself.

**Comment by meglomainiac** [comment]
"I don't care what "correct terminology" you want to prescribe to" It's hard to have a conversation with people if they don't understand the words they are using, it becomes pointless. The fact that people believe they can say words mean whatever they want at any given time is a major issue.

The fact that the save files have a different format is fine but it doesn't people the right or excuse to incorrectly use words then try to convince others to be just as ignorant.

The reason I made a account and posted about this issue is because many people were talking to me about how it was broken since the update and even though I explained they could use nomnom as it works, they were adamant that they wanted to use your save editor instead.

The fact is that the save editor is not working properly with the "open file/path", it is not working most of the time in 1.15.2 or at all in 1.15.3 of your save editor on windows 11. If you play on Steam instead of Game Pass it makes no difference if you can't even tell the editor where the save files are. It was working on earlier versions.

With this issue even if it could read/write the saves correctly it wouldn't matter.

At this point I don't care, feel free to delete the thread.

**Comment by goatfungus** [comment]
It's all good @meglomainiac, I just needed more info on which version of the game you were using.

Anyway, let's move on. I have just released an update which has improved WGS/XBox support as well as a number of fixes for the file dialogs. I hope this new version helps you out :)

**Comment by meglomainiac** [comment]
The "open file/path" is still buggy but occasionally works since your last update.

If you get it to select Game Pass/Steam the file path will stay there, assuming it shows up but once you do eventually get it to work it will not allow you to "open file/path" and change the file path to say Steam from Game Pass.

Not sure why it opens sometimes but not others however if you get it to work it now can read/load Game Pass saves.

**Comment by goatfungus** [comment]
There was an issue with the meta data file, but i think I have sorted it now. Let me know how it goes.

**Comment by meglomainiac** [comment]
The "open file/path" is still buggy, it did work sporadically in version 1.15.3 but in 1.15.5 it doesn't work at all.

Tried restarting the editor over 30 times in a row and it still didn't work

I deleted the  folder and extracted it again but it didn't work at all.
