### ISSUE TITLE
Save editor still not working for Xbox/Microsoft store :(

### ISSUE THREAD

**Issue by Chariot7000** [goatfungus/NMSSaveEditor#978]
After yesterday update the save slot don't appear as [Empty] anymore, but any change made on save editor is reverted back when entering the game, can't edit settlements, add items or apply any type of change with the save editor unfortunately.

In-game is shown that the last save was made on the same time I saved on save editor, but without any changes applied to the save :(

**Comment by Chariot7000** [comment]
I did a few more tests and sometimes when I save in the save editor the save gets erased, for example if I use the slot manual save to edit on save editor when I enter the game the game will only load the automatic save and if I go to the menu to load the manual save it will appear that there is no save data to load on manual save.

**Comment by goatfungus** [comment]
That's really weird.... I'll keep looking for a solution.

**Comment by Chariot7000** [comment]
I also tested by saving with both slots and when I enter the game sends me to the beginning of the game screen, it's like if I made a new save, I have to press square/x on the white beginning screen.

**Comment by Chariot7000** [comment]
If you need a version of the game on MS I can let you use a secondary account that I have that has NMS on it

**Comment by goatfungus** [comment]
I think I know what the problem is, so no need to share accounts. Will take a few hours to sort out though.

**Comment by goatfungus** [comment]
Ok, I have just released a new version which should fix the problem. Let me know how it goes.

**Comment by Chariot7000** [comment]
Unfortunately is still not working :(


I noticed that when I save on save editor the "Slot1Auto" transforms into "msbackup", same for "Slot1Manual" also the first slot is always "msbackup"



Also still doesn't apply the changes and sometimes my save gets reset to start of the game :(

**Comment by goatfungus** [comment]
Those will be old backups, so it might pay to delete all the msbackup files out of the backups folder before trying again. If you open any of those old backups and hit "Save" it will be writing a bad version of the meta data.

You need to start with a fresh working copy of your save data.

**Comment by Chariot7000** [comment]
I will try

**Comment by Chariot7000** [comment]
I tested again and deleted the backups but it's still the same, when I save there are no changes or my save reset to the beginning 🥺

**Comment by goatfungus** [comment]
Ok, I think I have finally figured it out and have released a new version, 1.15.6.
Please try again and let me know if this works for you.

**Comment by Chariot7000** [comment]
It's working perfectly now ty :3 🎉❤️

**Comment by HillBillyBong** [comment]
Everything seems to work fine but import and export of multi-tools. Thanks!

**Comment by SirCathal** [comment]
Yes it works now!
Thank you very much!

**Comment by goatfungus** [comment]
Excellent! Thanks to all of you who sent their save files for me to dissect, it was really helpful.

**Comment by OmegaX123** [comment]
Adding my voice to this: I have the latest updated version (and PC Game Pass version of he game), trying to edit my save seems to have unpredictable effects - the first time I tried, it wouldn't load the edited version but instead loaded the slightly-older manual save, and when I tried making the same edits to both it went back to the new game startup/initialization. Then I double-checked I had the latest version (there had been an update between the first issue and then, so I updated), and now editing my save causes the game to freeze when loading the save. I'm making simple changes, just unlocking and expanding my inventory and moving items around/from exosuit to ship, not even messing with the json editing or anything.

**Comment by ObservantNarwhal** [comment]
Hello, The folders inside wgs/(random number) are completely empty for me. Judging by everyone's previous comments I must be doing something wrong but I do not know what it is.

**Comment by SirCathal** [comment]
It is best to try the following procedure:

1. Rename the wgs folder to wgs.old
2. Start the game, then all saves are downloaded from the cloud and the wgs folder is recreated. You can then be sure that only valid saves are contained there
3. Wait 5 minutes for the autosave to be updated
4. Close the game 
5. Wait 1 minute (the store version locks the savegame folder a few seconds after the exit)
6. Start editor, edit, save
7. Start the game again. 
8. You may (not always) receive a message that the local saves are different from those in the cloud. When asked which ones should be used, select the local ones.

This should work. I have just tested again with the current game and editor version.

**Comment by ObservantNarwhal** [comment]
Thank you for the thorough explanation. This helps a lot!
